ecomproject/sahara/cart/urls.py
from . import views
from django.urls import path

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name = 'add_cart'),
    path('', views.cart_detail, name = 'cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name = 'cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name = 'full_remove'),
]

ecomproject/sahara/ecomapp/urls.py
from . import views
from django.urls import path
app_name = 'ecomapp'

urlpatterns = [
    path('', views.allProdCat, name = 'allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name = 'product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.ProDetail, name = 'proCatdetail')
]

ecomproject/sahara/sahara/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home', include('ecomapp.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecomproject/sahara/search_app/urls.py
from django.urls import path
from . import views

app_name = 'search_app'

urlpatterns = [
    path('',views.SearchResult, name = 'SearchResult')
]

ecomproject/sahara/cart/models.py
from django.db import models
from ecomapp.models import Product
# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem (models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecomproject/sahara/ecomapp/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=250, unique= True)
    slug = models.SlugField(max_length=250, unique= True)
    description = models.TextField(blank= True)
    image = models.ImageField(upload_to='category', blank= True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('ecomapp:product_by_category', args = [self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

    def get_url(self):
        return reverse('ecomapp:proCatdetail', args = [self.category.slug, self.slug])

ecomproject/sahara/search_app/models.py
from django.db import models

# Create your models here.

ecomproject/sahara/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecomapp.models import Product
from . models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id = _cart_id(request))

    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id = _cart_id(request))
        cart.save()

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()

    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product = product, quantity = 1, cart=cart)
        cart_item.save()

    return redirect('cart:cart_detail')

def cart_detail (request, total = 0, counter = 0, cart_items = None):
    try:
        cart = Cart.objects.get(cart_id = _cart_id(request))
        cart_items = CartItem.objects.filter(cart = cart, active = True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except:
        pass
    return render(request, 'cart.html', dict(cart_items = cart_items, total = total, counter = counter))

def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id = _cart_id(request))
    product = get_object_or_404(Product, id = product_id)
    cart_item = CartItem.objects.get(product = product, cart = cart)

    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()

    else:
        cart_item.delete()

    return redirect('cart:cart_detail')

def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id = _cart_id(request))
    product = get_object_or_404(Product, id = product_id)
    cart_item = CartItem.objects.get(product = product, cart = cart)

    cart_item.delete()
    return redirect('cart:cart_detail')

ecomproject/sahara/ecomapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage
# Create your views here.

def index(request):
    return HttpResponse ("HELLO")

def allProdCat (request, c_slug = None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404 (Category, slug = c_slug)
        products_list = Product.objects.all().filter(category =c_page, available = True)

    else:
        products_list = Product.objects.all().filter(available = True)
    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)
    return render(request, "category.html", {'category' : c_page, 'products' : products})

def ProDetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug = c_slug, slug = product_slug)
    except Exception as e:
        raise e
    return render(request, "product.html", {'product' : product})

ecomproject/sahara/search_app/views.py
from django.shortcuts import render
from ecomapp.models import Product
from django.db.models import Q

def SearchResult(request):
    products = None
    query = None

    if 'q'in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains = query) | Q(description__contains = query))
        return render(request, 'search.html', {'query' : query, 'products' : products})

ecomproject/sahara/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Reggae+One&display=swap" rel="stylesheet">
    <script src="https://use.fontawesome.com/b1201ffbf1.js"></script>
    <title> {% block title %} {% endblock %} </title>
    <style> body { background-image : linear-gradient(90deg, rgba(255,255,255,1) 0%, rgba(255,255,255,1) 43%, rgba(0,212,255,1) 100%); }</style>
</head>
<body>
<div class="container">

<!--  {% include 'header.html' %}-->
  {% include 'navbar.html' %}
  {% block content %}
  {% endblock %}
</div>
<div class="footer text-center">
  {% include 'footer.html' %}
</div>

<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

ecomproject/sahara/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
 Your Cart preview. Add more items or click 'buy' to proceed to payment.
{% endblock %}
{% block title %}
Cart - Sahara.in
{% endblock %}
{% block content %}

{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my-title">Your cart is empty</h1>
        <br>
        <p class="text-center">Click <a href="{% url 'ecomapp:allProdCat' %}">Here</a> to continue shopping</p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my-title">Your Shopping Cart</h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="my-table">
            <thead class="thead1">
                <tr>
                    <th colspan="5">Your Items</th>
                </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom image" height="100" width="130" style="overflow : hidden;"></a>
                </td>
                <td class="text-left">
                    {{cart_item.product.name}}
                    <br>
                    SKU : {{cart_item.product.id}}
                    <br>
                    Price : {{cart_item.product.price}}/-
                    <br>
                    QTY : <mark>{{cart_item.quantity}}</mark> x "{{cart_item}}"
                    <br>
                    Total Price : <b>{{cart_item.sub_total}}</b>/-
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}"><i class="fa fa-cart-plus"></i></a>&nbsp;
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}"><i class="fa fa-minus-circle"></i></a>&nbsp;
                    <a href="{% url 'cart:full_remove' cart_item.product.id %}"><i class="fa fa-trash"></i></a>&nbsp;
                </td>
                {% else %}
                <td>
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}"><i class="fa fa-minus-circle"></i></a>&nbsp;
                    <a href="{% url 'cart:full_remove' cart_item.product.id %}"><i class="fa fa-trash"></i></a>&nbsp;
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my-table">
            <thead class="thead1">
                <tr>
                    <th>CHECKOUT</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        Your Total Amount is: <b>{{total}}</b>/-
                    </td>
                </tr>
                <tr>
                    <td>Please review your cart items before proceeding to the payment page.</td>
                </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'ecomapp:allProdCat' %}" class="btn btn-primary btn-block">Continue Shopping <i class="fa fa-shopping-bag"></i></a>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

ecomproject/sahara/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
  {% if category %}
    {{ category.description|truncatewords:155}}
  {% else %}
    Welcome to Sahara, Where you can purchase premium goods at market disrupting prices.
  {% endif %}
{% endblock %}

{% block title %}
  {% if category %}
    {{category.name}} - Sahara
  {% else %}
    Sahara - One Stop Shop
  {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
      <div>
        <div>
          <p><a href="{% url 'ecomapp:allProdCat' %}">Product Collections</a></p>
        </div>
      </div>
    {% endif %}

  {% if category %}
    <div style="display : inline-block;">
      <img src="{{category.image.url}}" alt="{{category.name}}" width="80" height="80" style="border-radius: 50%; display: in-line">
      <h3>{{category.name}}</h3>
    </div>
  <br>
    <div>
      <p>{{category.desciption}}</p>
    </div>
  {% else %}
    <div>
      <img class="image-center" src="{% static 'img/banner1.png' %}" alt="Our products" height="390" width="1300">
    </div>
  <br>
  <div>
    <h1 class="text-center product-text">Our product Collections</h1>
    <p class="font-monospace text-center">Dummy text is text that is used in the publishing industry or by web designers to occupy the space which will later be filled with 'real' content. This is required when, for example, the final text is not yet available. Dummy text is also known as 'fill text'. It is said that song composers of the past used dummy texts as lyrics when writing melodies in order to have a 'ready-made' text to sing with the melody. Dummy texts have been in use by typesetters since the 16th century.</p>
  </div>
  {% endif %}
  <div class="container">
    <div class="row">
      {% for product in products %}
      <div class="product-margin col-9 col-sm-12 col-md-4 col-lg-4">
          <div class="card text-center" style="min-width : 18rem;">
              <a class="card-img-top my-image" href="{{product.get_url}}"><img src="{{product.image.url}}" alt="{{product.name}}" style="width : 100%; height: 280px;"></a>
              <div class="card-body">
                <h4 class="card-title">{{product.name}}</h4>
                <p>₹{{product.price}}/-</p>
            </div>
          </div>
      </div>
      {% endfor %}
    </div>
  </div>
<div>

        <div class="mx-auto">
          {% if products.paginator.num_pages > 1 %}
          <hr>
          <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-secondary btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
          </div>
          {% endif %}
          <br>
</div>
  </div>
{% endblock %}

ecomproject/sahara/templates/footer.html
    <div>
      <p class="text-center">© Sahara Pvt Ltd. All rights reserved.
        <script>document.write(new Date().getFullYear());</script></p>
    </div>

ecomproject/sahara/templates/header.html
{% load static %}
<div>
<header>
  <center>
    <a href="{% url 'ecomapp:allProdCat' %}"><img src="{% static 'img/logo.png' %}" alt="logoimage" width="150" height="120"></a>
  </center>
</header>
</div>

ecomproject/sahara/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

ecomproject/sahara/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <a href="{% url 'ecomapp:allProdCat' %}"><img src="{% static 'img/logo.png' %}" alt="logoimage" width="90" height="70"></a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item btn btn-space">
          <a class="nav-link active btn btn-secondary rounded-pill shadow bg-white" aria-current="page" href="{% url 'ecomapp:allProdCat' %}"><b>Home</b></a>
        </li>
        <li class="nav-item btn btn-space">
          <a class="nav-link btn btn-secondary rounded-pill shadow bg-white" href="#">Offers</a>
        </li>
        <li class="nav-item dropdown {% if 'ecomapp' in request.path %} active {% endif %} btn btn-space">
          <a class="nav-link dropdown-toggle btn btn-secondary rounded-pill shadow bg-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'ecomapp:allProdCat' %}"><b>All Products</b></a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
        <li>
          <form class="d-flex" method="get" action="{% url 'search_app:SearchResult' %}">
            {% csrf_token %}
        <input style="margin-top: 10px;" class="form-control" type="search" placeholder="Search" aria-label="Search" name="q" size="40">
        <button style=" margin-top: 10px;" class="btn btn-outline-primary" type="submit"><i class="fa fa-search"></i></button>
      </form>
        </li>
      </ul>
      {% if item_count > 0 %}
        <div class="nav-item btn btn-space">
          <a style="color : black;" class="nav-link btn btn-secondary rounded-pill shadow bg-white" href="{% url 'cart:cart_detail' %}">Your Cart <i class="fa fa-shopping-cart"></i>({{item_count}})</a>
        </div>
      {% endif %}
    </div>
  </div>
</nav>

ecomproject/sahara/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
  {{product.description|truncatewords:155}}
{% endblock %}
  
{% block title %}
  {% if category %}
    {{product.name}} - Sahara
  {% endif %}
{% endblock %}

{% block content %}
  <div>
    <div>
      <p><a class="btn btn-info btn-sm" href="{% url 'ecomapp:allProdCat' %}">Home</a>| <a class="btn btn-info btn-sm" href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>
    </div>
  </div>
<br>
  <div class="container">
    <div class="row">
      <div class="prodimage col-md-6 col-sm-6 col-lg-6">
        <div>
        <img src="{{product.image.url}}" alt="{{product.name}}" height="220" width="250" style="overflow : hidden;">
        </div>
      </div>
    <div class="proddesc col-md-6 col-sm-6 col-lg-6">
    <div>
      <h1>{{product.name}}</h1>
      <p>₹{{product.price}}/-</p>
      <p>{{product.description}}</p>
      {% if product.stock <= 0 %}
      <p><b>Out Of Stock</b></p>
      {% else %}
      <a class="btn btn-outline-dark" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
      {% endif %}
    </div>
      </div>
      </div>
  </div>

{% endblock %}

ecomproject/sahara/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
Search in our never-ending products
{% endblock %}
{% block title %}
Search
{% endblock %}

{% block content %}
<div>
    <p class="text-center search_text">You have searched for :<b>"{{query}}"</b></p>
</div>


<div class="container">
  <div class="row mx-auto">
      {% for product in products %}
      <div class="product-margin col-9 col-sm-12 col-md-4 col-lg-4">
          <div class="card text-center" style="min-width : 18rem;">
              <a class="card-img-top my-image" href="{{product.get_url}}"><img src="{{product.image.url}}" alt="{{product.name}}" style="width : 100%; height: 280px;"></a>
              <div class="card-body">
                 <h4 class="card-title">{{product.name}}</h4>
                  <p>₹{{product.price}}/-</p>
              </div>
          </div>
      </div>
      {% endfor %}
  </div>
</div>
      {% for product in products %}
      {% empty %}
      <div class="row mx-auto">
          <p class="text-center search_text">"0" Results found</p>
      </div>
      {% endfor %}
{% endblock %}